const SUPABASE_URL = "https://elobmhhdblluzumiqfmp.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_N18S_C93EG8adwRJ0cTYRA_3F6kPYfH";
const $=id=>document.getElementById(id);let room=null,hostMode=false;
function show(id){$(id).classList.remove('hidden')}function hide(id){$(id).classList.add('hidden')}function err(id,msg){$(id).textContent=msg||''}
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
async function rpc(fn,args){const r=await fetch(SUPABASE_URL+'/rest/v1/rpc/'+fn,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_ANON_KEY,'Authorization':'Bearer '+SUPABASE_ANON_KEY},body:JSON.stringify(args)});let data;try{data=await r.json()}catch{data={}}if(!r.ok)throw Error(data.message||data.details||JSON.stringify(data));return data}
function urlRoom(c){const base=location.pathname.split('/room/')[0].replace(/\/$/,'');history.replaceState(null,'',base+'/room/'+c)}
async function open(c){room=c;hide('home');hide('create');show('room');$('roomCode').textContent=c;urlRoom(c);$('hostPanel').classList.add('hidden');$('startedPanel').classList.add('hidden');await refresh()}
async function refresh(){if(!room)return;try{const d=await rpc('room_status',{p_code:room});$('rosterCount').textContent=`현재 ${d.participants.length}명 참가 · 인원 제한 없음 · 상태: ${d.started?'추첨 완료':'등록 중'}`;$('roster').innerHTML='';d.participants.forEach(n=>{const li=document.createElement('li');li.textContent=n;$('roster').append(li)});if(d.started){show('startedPanel');hide('hostPanel')}else{hide('startedPanel');if(hostMode)show('hostPanel');else hide('hostPanel')}}catch(e){err('registerError',e.message)}}
$('createRoom').onclick=()=>{hide('home');show('create');err('createError','')};$('createBack').onclick=()=>{hide('create');show('home')};
$('createSubmit').onclick=async()=>{const name=$('hostName').value.trim(),pw=$('hostPass').value;if(!name||pw.length<6){err('createError','이름을 입력하고 방장 비밀번호를 6자 이상 설정해주세요.');return}try{let c=code();await rpc('create_room',{p_code:c,p_host_name:name,p_host_password:pw});hostMode=true;await open(c);$('personName').value=name;$('personPass').value='';}catch(e){err('createError',e.message)}};
$('joinRoom').onclick=async()=>{const c=$('roomKey').value.trim().toUpperCase();err('homeError','');if(!/^[A-Z0-9]{6}$/.test(c)){err('homeError','6자리 방 키를 입력해주세요.');return}hostMode=false;try{await open(c)}catch(e){err('homeError',e.message)}};$('roomKey').addEventListener('keydown',e=>{if(e.key==='Enter')$('joinRoom').click()});
$('register').onclick=async()=>{const n=$('personName').value.trim(),pw=$('personPass').value,avoid=$('avoid').value.trim();if(!n||pw.length<6){err('registerError','이름을 입력하고 비밀번호를 6자 이상 설정해주세요.');return}try{await rpc('register_person',{p_code:room,p_name:n,p_password:pw,p_avoid:avoid});err('registerError','등록했어요!');await refresh()}catch(e){err('registerError',e.message)}};
$('start').onclick=async()=>{try{await rpc('start_draw',{p_code:room,p_host_password:$('hostPassStart').value});err('startError','추첨 완료!');await refresh()}catch(e){err('startError',e.message)}};
$('reveal').onclick=async()=>{try{const d=await rpc('reveal_result',{p_code:room,p_name:$('revealName').value.trim(),p_password:$('revealPass').value});$('result').textContent=`🎁 ${d.recipient}님
받고 싶지 않은 것: ${d.avoid||'등록된 내용 없음'}`}catch(e){$('result').textContent=e.message}};
$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('copyLink').textContent='✓ 복사 완료'}catch{err('registerError','링크 복사 권한이 없어요. 주소창에서 복사해주세요.')}};$('refresh').onclick=refresh;$('backHome').onclick=()=>{room=null;hostMode=false;hide('room');show('home');history.replaceState(null,'',location.pathname.split('/room/')[0].replace(/\/$/,'')+'/')};
(function(){const m=location.pathname.match(/\/room\/([^/]+)/i);if(m){hostMode=false;open(m[1].toUpperCase())}})();