create table if not exists public.rooms (
 id bigint generated by default as identity primary key,
 room_code text unique not null,
 participants jsonb not null,
 assignments jsonb not null,
 created_at timestamptz default now()
);
alter table public.rooms enable row level security;
create policy "rooms can be read" on public.rooms for select to anon using (true);
create policy "rooms can be created" on public.rooms for insert to anon with check (true);
